import { pgTable, serial, text, integer, numeric, timestamp } from "drizzle-orm/pg-core";

export const closedTicketsTable = pgTable("closed_tickets", {
  id: serial("id").primaryKey(),
  uploadId: integer("upload_id").notNull(),
  ticketId: text("ticket_id").notNull(),
  createdOn: text("created_on"),
  customerType: text("customer_type"),
  customerCategory: text("customer_category"),
  customerName: text("customer_name"),
  city: text("city"),
  state: text("state"),
  rsh: text("rsh"),
  rshEmail: text("rsh_email"),
  servicePartnerName: text("service_partner_name"),
  servicePartnerEmail: text("service_partner_email"),
  ash: text("ash"),
  ashPhone: text("ash_phone"),
  category: text("category"),
  product: text("product"),
  serialNumber: text("serial_number"),
  support: text("support"),
  supportType: text("support_type"),
  invoiceDate: text("invoice_date"),
  invoiceNumber: text("invoice_number"),
  installationDate: text("installation_date"),
  territoryType: text("territory_type"),
  ticketType: text("ticket_type"),
  serviceType: text("service_type"),
  problemDescription: text("problem_description"),
  ticketPriority: text("ticket_priority"),
  ticketStatus: text("ticket_status"),
  wipSubStage: text("wip_sub_stage"),
  lastAction: text("last_action"),
  ticketTerritory: text("ticket_territory"),
  components: text("components"),
  reOpenTicket: text("re_open_ticket"),
  repeatTicket: text("repeat_ticket"),
  freeOfCost: text("free_of_cost"),
  paymentType: text("payment_type"),
  paymentValue: numeric("payment_value"),
  territoryCategory: text("territory_category"),
  // Closure fields
  closureRemarks: text("closure_remarks"),
  closureComments: text("closure_comments"),
  technicianClosedDate: text("technician_closed_date"),
  partiallyClosedByEcp: text("partially_closed_by_ecp"),
  partiallyClosedDate: text("partially_closed_date"),
  partiallyClosedByAshRsh: text("partially_closed_by_ash_rsh"),
  closedFrom: text("closed_from"),
  closedDate: text("closed_date"),
  totalDuration: text("total_duration"),
  tatMinutes: numeric("tat_minutes"),
  distanceTravelled: text("distance_travelled"),
  closureType: text("closure_type"),
  serviceReportNumber: text("service_report_number"),
  ticketClosedBy: text("ticket_closed_by"),
  consumedComponents: text("consumed_components"),
  importedAt: timestamp("imported_at", { withTimezone: true }).notNull().defaultNow(),
});

export type ClosedTicket = typeof closedTicketsTable.$inferSelect;
