import { pgTable, serial, text, integer, timestamp } from "drizzle-orm/pg-core";

export const mrfDataTable = pgTable("mrf_data", {
  id: serial("id").primaryKey(),
  uploadId: integer("upload_id").notNull(),
  ticketId: text("ticket_id").notNull(),
  createdOn: text("created_on"),
  customerName: text("customer_name"),
  state: text("state"),
  rsh: text("rsh"),
  rshEmail: text("rsh_email"),
  servicePartnerName: text("service_partner_name"),
  ash: text("ash"),
  category: text("category"),
  product: text("product"),
  supportType: text("support_type"),
  ticketType: text("ticket_type"),
  // MRF specific fields
  mrfNo: text("mrf_no"),
  mrfCreatedDate: text("mrf_created_date"),
  componentName: text("component_name"),
  partCode: text("part_code"),
  description: text("description"),
  quantity: integer("quantity").default(0),
  remarks: text("remarks"),
  componentToBeIssuedFrom: text("component_to_be_issued_from"),
  dispatchTo: text("dispatch_to"),
  dispatchCity: text("dispatch_city"),
  dispatchState: text("dispatch_state"),
  contactName: text("contact_name"),
  contactNumber: text("contact_number"),
  mrfStatus: text("mrf_status"),
  mrfRequestedBy: text("mrf_requested_by"),
  ashApprovedDate: text("ash_approved_date"),
  approvedBy: text("approved_by"),
  approvedDate: text("approved_date"),
  dispatchFrom: text("dispatch_from"),
  dispatchDate: text("dispatch_date"),
  courierName: text("courier_name"),
  docketNo: text("docket_no"),
  deliveryDate: text("delivery_date"),
  orgStockApprovedQty: integer("org_stock_approved_qty").default(0),
  ownStockApprovedQty: integer("own_stock_approved_qty").default(0),
  importedAt: timestamp("imported_at", { withTimezone: true }).notNull().defaultNow(),
});

export type MrfData = typeof mrfDataTable.$inferSelect;
